name: CI

on:
  push:
  schedule:
    - cron: 15 3 */1 * *

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - snapshot

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v1
    - name: Run tests and linters
      run: make all
